language: node_js
node_js:
  - '0.10'
  - '0.12'
notifications:
  - slack: insuperable-arete:c5vFufBHIzIlotTw1kFXEB6p
before_install:
  - npm install -g bower
  - npm update -g
install:
  - npm install
  - bower install
